DROP TRIGGER IF EXISTS TRIGGER_POST_LIKE_CNT ON PUBLIC.OUTMOON_POST_LIKE;
DROP FUNCTION IF EXISTS PUBLIC.POST_LIKE_CNT();
DROP TRIGGER IF EXISTS TRIGGER_CMT_LIKE_CNT ON PUBLIC.OUTMOON_CMT_LIKE;
DROP FUNCTION IF EXISTS PUBLIC.CMT_LIKE_CNT();
DROP TRIGGER IF EXISTS TRIGGER_POST_COMMENT_CNT ON PUBLIC.OUTMOON_CMT;
DROP FUNCTION IF EXISTS PUBLIC.POST_COMMENT_CNT();
DROP TRIGGER IF EXISTS TRIGGER_USER_POST_CNT ON PUBLIC.OUTMOON_POST;
DROP FUNCTION IF EXISTS PUBLIC.USER_POST_CNT();
DROP TRIGGER IF EXISTS TRIGGER_POST_HASHTAG_USED_CNT ON PUBLIC.OUTMOON_LINK_POST_HASH;
DROP FUNCTION IF EXISTS POST_HASHTAG_USED_CNT();
DROP TRIGGER IF EXISTS TRIGGER_CMT_HASHTAG_USED_CNT ON PUBLIC.OUTMOON_LINK_CMT_HASH ;
DROP FUNCTION IF EXISTS CMT_HASHTAG_USED_CNT();

DROP FUNCTION IF EXISTS public.tagging_post(_varchar,int8);
DROP FUNCTION IF EXISTS public.tagging_cmt(_varchar,int8);

--해쉬태그_POST 처리하는 procedure
CREATE OR REPLACE FUNCTION tagging_post(varchar[], BIGINT) RETURNS INTEGER AS $TAGGING_POST$
DECLARE 
	a_tags 	ALIAS FOR $1;
	a_post_id ALIAS FOR $2;
	v_val	VARCHAR;
	v_id	BIGINT;
	result int := 0;
	
BEGIN 
	FOREACH v_val IN ARRAY a_tags
	LOOP
		SELECT id INTO v_id
			FROM outmoon_hashtag
			WHERE tag = v_val;
		IF(v_id IS NOT NULL) THEN 
			RAISE NOTICE 'v_val: %', v_val;
			RAISE NOTICE 'v_id: %', v_id;
		ELSE
			INSERT INTO outmoon_hashtag (
				tag
			)values(
				v_val
			);
		
			SELECT currval(pg_get_serial_sequence('outmoon_hashtag','id')) INTO v_id;	
		
			RAISE NOTICE 'v_val: %', v_val;
			RAISE NOTICE 'v_id: %', v_id;
			
		END IF;
	
		INSERT INTO outmoon_link_post_hash (
				post_id,
				tag_id
			)VALUES(
				a_post_id,
				v_id
			);
		RESULT := RESULT + 1;
	
	END LOOP;
	RETURN RESULT;
END;
$TAGGING_POST$ LANGUAGE PLPGSQL;

--해쉬태그_POST 처리하는 procedure
CREATE OR REPLACE FUNCTION tagging_cmt(varchar[], BIGINT) RETURNS INTEGER AS $TAGGING_CMT$
DECLARE 
	a_tags 	ALIAS FOR $1;
	a_cmt_id ALIAS FOR $2;
	v_val	VARCHAR;
	v_id	BIGINT;
	result int := 0;
	
BEGIN 
	FOREACH v_val IN ARRAY a_tags
	LOOP
		SELECT id INTO v_id
			FROM outmoon_hashtag
			WHERE tag = v_val;
		IF(v_id IS NOT NULL) THEN 
			RAISE NOTICE 'v_val: %', v_val;
			RAISE NOTICE 'v_id: %', v_id;
		ELSE
			INSERT INTO outmoon_hashtag (
				tag
			)values(
				v_val
			);
		
			SELECT currval(pg_get_serial_sequence('outmoon_hashtag','id')) INTO v_id;	
		
			RAISE NOTICE 'v_val: %', v_val;
			RAISE NOTICE 'v_id: %', v_id;
			
		END IF;
	
		INSERT INTO outmoon_link_cmt_hash (
				cmt_id,
				tag_id
			)VALUES(
				a_cmt_id,
				v_id
			);
		RESULT := RESULT + 1;
	
	END LOOP;
	RETURN RESULT;
END;
$TAGGING_CMT$ LANGUAGE PLPGSQL;


--POST에 대한 좋아요 트리거 함수 
CREATE OR REPLACE FUNCTION POST_LIKE_CNT() RETURNS TRIGGER AS $TRIGGER_POST_LIKE_CNT$
DECLARE COUNT INT;

BEGIN
	IF(TG_OP = 'INSERT') THEN
		SELECT COUNT(*) INTO COUNT 
			FROM OUTMOON_POST_LIKE 
			WHERE POST_ID = NEW.POST_ID;

		UPDATE OUTMOON_POST
			SET LIKE_CNT = COUNT
			WHERE ID = NEW.POST_ID;
		RETURN NEW;
	
	ELSEIF(TG_OP = 'DELETE') THEN
		SELECT COUNT(*) INTO COUNT
			FROM OUTMOON_POST_LIKE 
			WHERE POST_ID = OLD.POST_ID;
		
		UPDATE OUTMOON_POST 
			SET LIKE_CNT = COUNT
			WHERE ID = OLD.POST_ID;
		RETURN OLD;
	END IF;
	
	RETURN NULL;
		
END;

$TRIGGER_POST_LIKE_CNT$ LANGUAGE PLPGSQL;

--COMMENT 에 대한 좋아요 트리거 함수
CREATE OR REPLACE FUNCTION CMT_LIKE_CNT() RETURNS TRIGGER AS $TRIGGER_CMT_LIKE_CNT$
DECLARE COUNT INT;

BEGIN
	IF(TG_OP = 'INSERT') THEN
		SELECT COUNT(*) INTO COUNT
			FROM OUTMOON_CMT_LIKE
			WHERE CMT_ID =  NEW.CMT_ID;
		
		UPDATE OUTMOON_CMT 
			SET LIKE_CNT = COUNT
			WHERE ID = NEW.CMT_ID;
		
		RETURN NEW;
	ELSEIF(TG_OP = 'DELETE') THEN
		SELECT COUNT(*) INTO COUNT
			FROM OUTMOON_CMT_LIKE
			WHERE CMT_ID  = OLD.CMT_ID;
		
		UPDATE OUTMOON_CMT 
			SET LIKE_CNT = COUNT
			WHERE ID = OLD.CMT_ID;
		
		RETURN OLD;
	END IF;

	RETURN NULL;
END;
$TRIGGER_CMT_LIKE_CNT$ LANGUAGE PLPGSQL;


--게시물에 대한 댓글 갯수 트리거 함수
--댓글에 대한 대댓글 갯수 트리거 함수
CREATE OR REPLACE FUNCTION POST_COMMENT_CNT() RETURNS TRIGGER AS $TRIGGER_POST_COMMENT_CNT$
DECLARE COUNT INT;

BEGIN
	IF(TG_OP = 'INSERT') THEN
	
--		대댓글인 경우, PARENT CMT의 댓글 갯수 업데이트
		IF(NEW.PARENT_ID != 0) THEN
			SELECT COUNT(*) INTO COUNT
				FROM OUTMOON_CMT
				WHERE PARENT_ID =  NEW.PARENT_ID;
			
			UPDATE OUTMOON_CMT 
				SET COMMENT_CNT = COUNT
				WHERE ID = NEW.PARENT_ID;
			
			RAISE NOTICE 'POST_ID IS %', NEW.POST_ID;
			RAISE NOTICE 'PARENT_ID IS %', NEW.PARENT_ID;
		END IF;
	
		SELECT COUNT(*) INTO COUNT
			FROM OUTMOON_CMT
			WHERE POST_ID =  NEW.POST_ID;
		
		UPDATE OUTMOON_POST 
			SET COMMENT_CNT = COUNT
			WHERE ID = NEW.POST_ID;
		
		RAISE NOTICE 'POST_ID IS %', NEW.POST_ID;
		RAISE NOTICE 'PARENT_ID IS %', NEW.PARENT_ID;
		
		RETURN NEW;
	
	ELSEIF(TG_OP = 'DELETE') THEN
	
--		대댓글인 경우 PARENT CMT의 댓글 갯수 업데이트
		IF(OLD.PARENT_ID != 0) THEN
			SELECT COUNT(*) INTO COUNT
				FROM OUTMOON_CMT
				WHERE PARENT_ID  = OLD.PARENT_ID;
			
			UPDATE OUTMOON_CMT 
				SET COMMENT_CNT = COUNT
				WHERE ID = OLD.PARENT_ID;
		END IF;
	
	
--		PARENT CMT가 삭제될 때, CHILREN CMT도 같이 삭제되도록.. 제약조건 때문에..BEFOR로 트리거 설정해야하나...
		DELETE 
			FROM OUTMOON_CMT 
			WHERE PARENT_ID = OLD.ID;
	
		SELECT COUNT(*) INTO COUNT
			FROM OUTMOON_CMT
			WHERE POST_ID  = OLD.POST_ID;
		
		UPDATE OUTMOON_POST 
			SET COMMENT_CNT = COUNT
			WHERE ID = OLD.POST_ID;
		
		RAISE NOTICE 'POST_ID IS %', OLD.POST_ID;
		RAISE NOTICE 'PARENT_ID IS %', OLD.PARENT_ID;
		
		RETURN OLD;
	END IF;
	RETURN NULL;
END;
$TRIGGER_POST_COMMENT_CNT$ LANGUAGE PLPGSQL;


--COMMENT 에 대한 좋아요 트리거 함수
CREATE OR REPLACE FUNCTION USER_POST_CNT() RETURNS TRIGGER AS $TRIGGER_USER_POST_CNT$
DECLARE COUNT INT;

BEGIN
	IF(TG_OP = 'INSERT') THEN
		SELECT COUNT(*) INTO COUNT
			FROM OUTMOON_POST
			WHERE WRITER_ID =  NEW.WRITER_ID;
		
		UPDATE OUTMOON_USER 
			SET POST_CNT = COUNT
			WHERE ID = NEW.WRITER_ID;
		
		RETURN NEW;
--	POST는 FLAG로 DELETE여부를 처리하기 때문에.. TRIGGER가 일어날 OPERATION를 UPDATE로 설정하겠다.	
	ELSEIF(TG_OP = 'DELETE') THEN
		SELECT COUNT(*) INTO COUNT
			FROM OUTMOON_POST
			WHERE WRITER_ID  = OLD.WRITER_ID;
		
		UPDATE OUTMOON_USER 
			SET POST_CNT = COUNT
			WHERE ID = OLD.WRITER_ID;
		
		RETURN OLD;
	END IF;

	RETURN NULL;
END;
$TRIGGER_USER_POST_CNT$ LANGUAGE PLPGSQL;

--link_post_hash에 대한 tag_cnt 트리거 함수
CREATE OR REPLACE FUNCTION POST_HASHTAG_USED_CNT() RETURNS TRIGGER AS $TRIGGER_POST_HASHTAG_USED_CNT$
DECLARE count INT;

BEGIN
	IF(TG_OP = 'INSERT') THEN
		SELECT COUNT(*) INTO count
			FROM outmoon_link_post_hash
			WHERE tag_id = NEW.tag_id;
		
		UPDATE outmoon_hashtag 
			SET used_cnt = count
			WHERE id = NEW.tag_id;
		RETURN NEW;
	
	ELSEIF(TG_OP = "DELETE") THEN
		SELECT COUNT(*) INTO count
			FROM outmoon_link_post_hash
			WHERE tag_id = OLD.tag_id;
		
		UPDATE outmoon_hashtag 
			SET used_cnt = count
			WHERE id = OLD.tag_id;
		RETURN OLD;
	END IF;
	RETURN NULL;
END;
$TRIGGER_POST_HASHTAG_USED_CNT$ LANGUAGE PLPGSQL;

--link_cmt_hash에 대한 tag_cnt 트리거 함수
CREATE OR REPLACE FUNCTION CMT_HASHTAG_USED_CNT() RETURNS TRIGGER AS $TRIGGER_CMT_HASHTAG_USED_CNT$
DECLARE count INT;

BEGIN
	IF(TG_OP = 'INSERT') THEN
		SELECT COUNT(*) INTO count
			FROM outmoon_link_cmt_hash 
			WHERE tag_id = NEW.tag_id;
		
		UPDATE outmoon_hashtag 
			SET used_cnt = count
			WHERE id = NEW.tag_id;
		RETURN NEW;
	
	ELSEIF(TG_OP = "DELETE") THEN
		SELECT COUNT(*) INTO count
			FROM outmoon_link_cmt_hash 
			WHERE tag_id = OLD.tag_id;
		
		UPDATE outmoon_hashtag 
			SET used_cnt = count
			WHERE id = OLD.tag_id;
		RETURN OLD;
	END IF;
	RETURN NULL;
END;
$TRIGGER_CMT_HASHTAG_USED_CNT$ LANGUAGE PLPGSQL;

--트리거 생성
CREATE TRIGGER TRIGGER_POST_LIKE_CNT
	AFTER INSERT OR UPDATE OR DELETE 
	ON OUTMOON_POST_LIKE
	FOR EACH ROW EXECUTE PROCEDURE POST_LIKE_CNT();
	
CREATE TRIGGER TRIGGER_CMT_LIKE_CNT
	AFTER INSERT OR UPDATE OR DELETE 
	ON OUTMOON_CMT_LIKE
	FOR EACH  ROW EXECUTE PROCEDURE CMT_LIKE_CNT();

CREATE TRIGGER TRIGGER_POST_COMMENT_CNT
	AFTER INSERT OR UPDATE OR DELETE
	ON OUTMOON_CMT 
	FOR EACH ROW EXECUTE PROCEDURE POST_COMMENT_CNT();

CREATE TRIGGER TRIGGER_USER_POST_CNT
	AFTER INSERT OR UPDATE OR DELETE 
	ON OUTMOON_POST
	FOR EACH  ROW EXECUTE PROCEDURE USER_POST_CNT();
	
CREATE TRIGGER TRIGGER_POST_HASHTAG_USED_CNT
	AFTER INSERT OR UPDATE OR DELETE 
	ON OUTMOON_LINK_POST_HASH
	FOR EACH  ROW EXECUTE PROCEDURE POST_HASHTAG_USED_CNT();

CREATE TRIGGER TRIGGER_CMT_HASHTAG_USED_CNT
	AFTER INSERT OR UPDATE OR DELETE 
	ON OUTMOON_LINK_CMT_HASH
	FOR EACH  ROW EXECUTE PROCEDURE CMT_HASHTAG_USED_CNT();
