
CREATE OR REPLACE
FUNCTION POST_LIKE_COUNT() RETURNS TRIGGER AS $TRIGGER_POST_LIKE_COUNT$

DECLARE COUNT INT;
BEGIN
	IF(TG_OP = 'INSERT') THEN
		SELECT 
			COUNT(*) INTO COUNT 
		FROM 
			OUTMOON_POST_LIKE AS OP 
		WHERE 
			POST_ID = NEW.POST_ID;
		
		RAISE NOTICE 'THIS IS %', COUNT;
		RAISE NOTICE 'THIS IS %', NEW.POST_ID;
		
		UPDATE 
			OUTMOON_POST
		SET
			LIKE_CNT = COUNT
		WHERE
			ID = NEW.POST_ID;
		RETURN NEW;
	ELSEIF(TG_OP = 'DELETE') THEN
	
	END IF;
RETURN NULL;
END;

$TRIGGER_POST_LIKE_COUNT$ LANGUAGE plpgsql;

CREATE OR REPLACE
FUNCTION CMT_LIKE_COUNT() RETURNS TRIGGER AS $TRIGGER_LIKE


CREATE TRIGGER TRIGGER_POST_LIKE_COUNT AFTER
INSERT
	OR
UPDATE
	OR
DELETE
	ON
	OUTMOON_POST_LIKE FOR EACH ROW EXECUTE PROCEDURE POST_LIKE_COUNT();


